### ISSUE TITLE
add bluealsa-cli

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/pkgsource#1]
Now that bluez-alsa has been bumped to v4.0.0 please add `--enable-cli` to the list of configure options for it in `pkgsource/bluez-alsa/debian/rules` (and/or elsewhere as necessary).

Unlike `bluealsa-aplay` this utility is not built by default.

**Comment by moodeaudio** [comment]
What does the cli provide?

**Comment by TheOldPresbyope** [comment]
From man bluealsa-cli

> DESCRIPTION
       bluealsa-cli   provides   command-line   access   to   the   BlueALSA  D-Bus  API  "org.bluealsa.Manager1"  and
       "org.bluealsa.PCM1" interfaces and thus allows introspection and some control of BlueALSA PCMs while  they  are
       running.

See [bluealsa-cli](https://github.com/Arkq/bluez-alsa/blob/master/doc/bluealsa-cli.1.rst) for the complete description. 

Here's my moOde 8.2.5 player connected to my JBL Flip 2 bluetooth speaker, for example

```
pi@m825p4b:~ $ bluealsa-cli info /org/bluealsa/hci0/dev_00_1D_DF_AA_27_37/a2dpsrc/sink
Device: /org/bluez/hci0/dev_00_1D_DF_AA_27_37
Sequence: 0
Transport: A2DP-source
Mode: sink
Format: S16_LE
Channels: 2
Sampling: 48000 Hz
Available codecs: SBC
Selected codec: SBC
Delay: 15.0 ms
SoftVolume: Y
Volume: L: 127 R: 127
Muted: L: N R: N
```

**Comment by moodeaudio** [comment]
Could be useful. I'll run it by @bitkeeper

**Comment by bitkeeper** [comment]
No problem at all, I will add a patch for it to the build script.

**Comment by bitkeeper** [comment]
new version in the cs repo present.

**Comment by TheOldPresbyope** [comment]
Thanks. Tested new arm64 binary this morning.
