### ISSUE TITLE
moode+docker

### ISSUE THREAD

**Issue by jcor29** [moode-player/pkgsource#2]
Hi all,
Is there any docker image for arm64 ?
Just for a USB dac
thanks

**Comment by moodeaudio** [comment]
What's the usage scenario?

**Comment by jcor29** [comment]
Hi have a pi4 with multiple container,
I would like one with moode , Hence i coud use moode with my USB dac

Le mer. 11 sept. 2024, 20:24, Tim Curtis ***@***.***> a
écrit :

**Comment by jcor29** [comment]
I think picore does it btw

**Comment by moodeaudio** [comment]
A user on our Forum tried something with docker but ran into some show stopper issues. 

Here's are links to the Thread and the repo
https://moodeaudio.org/forum/showthread.php?tid=5759&highlight=docker
https://github.com/chourmovs/moode_debian

It's a no-go for me but maybe another dev will pick up on @ chourmovs work.

**Comment by jcor29** [comment]
ok , thanks for your feedback

Le mer. 11 sept. 2024 à 21:58, Tim Curtis ***@***.***> a
écrit :
